### ISSUE TITLE
Blok snel navigatie niet zichtbaar op cursuspagina

### ISSUE THREAD

**Issue by gemguardian** [Lesterhuis-Training-en-Consultancy/moodle-block_fastnav#1]
<p>Toevoegen van een 4 nieuwe weergave modus&nbsp;</p><ol><li>toon blok en zijbalk op cursusoverzicht pagina</li><li>toon blok op cursusoverzicht pagina</li><li>toon blok en zijbalk op cursusoverzicht én activiteiten pagina</li><li>toon blok op cursusoverzicht en activiteit pagina</li></ol><p>Deadline: oktober 2022</p><p>graag urenindicatie</p><p>&nbsp;</p> <br/>

**Comment by gemguardian** [comment]
<div class="panel panel-warning" style="border-color: #faebcc;margin-bottom: 20px;background-color: #fff;border: 1px solid transparent;border-radius: 4px;-webkit-box-shadow: 0 1px 1px rgb(0 0 0 / 5%);box-shadow: 0 1px 1px rgb(0 0 0 / 5%);font-size: 14px;">
                <div class="panel-heading" style="color: #8a6d3b;background-color: #fcf8e3;border-color: #faebcc;padding: 10px 15px;border-bottom: 1px solid transparent;border-top-left-radius: 3px;border-top-right-radius: 3px;">Comment from Freshservice:</div>
                <div class="panel-body" style="padding: 15px;">
                <strong>Freshservice:&nbsp;</strong><a href="https://ltnc.freshservice.com/itil/changes/79" target="_blank">79</a>&nbsp;linked successfully.
                </div>
                <div class="panel-footer" style="padding: 10px 15px;background-color: #f5f5f5;border-top: 1px solid #ddd;border-bottom-right-radius: 3px;border-bottom-left-radius: 3px;">
                Freshservice:&nbsp;<a href="https://ltnc.freshservice.com/itil/changes/79" target="_blank">#79</a>
                  <div class="pull-right" style="float:right">By: <em>Gemma Lesterhuis &lt;gemma@ltnc.nl&gt;</em></div>
                </div>
              </div>

**Comment by gemguardian** [comment]
@luukverhoeven zou jij een kostenindicatie kunnen geven voor het toevoegen van een weergave modus aan het Blok Snelnavigatie:

* Toon blok en zijbalk op cursusoverzicht én activiteiten pagina

Gaat om M39 - 

Hoor het graag.

**Comment by gemguardian** [comment]
<div class="panel panel-warning" style="border-color: #faebcc;margin-bottom: 20px;background-color: #fff;border: 1px solid transparent;border-radius: 4px;-webkit-box-shadow: 0 1px 1px rgb(0 0 0 / 5%);box-shadow: 0 1px 1px rgb(0 0 0 / 5%);font-size: 14px;">
                <div class="panel-heading" style="color: #8a6d3b;background-color: #fcf8e3;border-color: #faebcc;padding: 10px 15px;border-bottom: 1px solid transparent;border-top-left-radius: 3px;border-top-right-radius: 3px;">Comment from Freshservice:</div>
                <div class="panel-body" style="padding: 15px;">
                <strong>Freshservice:&nbsp;</strong><a href="https://ltnc.freshservice.com/helpdesk/tickets/9075" target="_blank">9075</a>&nbsp;linked successfully.
                </div>
                <div class="panel-footer" style="padding: 10px 15px;background-color: #f5f5f5;border-top: 1px solid #ddd;border-bottom-right-radius: 3px;border-bottom-left-radius: 3px;">
                Freshservice:&nbsp;<a href="https://ltnc.freshservice.com/helpdesk/tickets/9075" target="_blank">#9075</a>
                  <div class="pull-right" style="float:right">By: <em>Gemma Lesterhuis &lt;gemma@ltnc.nl&gt;</em></div>
                </div>
              </div>

**Comment by luukverhoeven** [comment]
Zie je dit als extra block opties voor je?

• Afhankelijk van de geselecteerde opties kan het blok tonen.

**Comment by gemguardian** [comment]
Ik zag het oorspronkelijk als een extra optie bij "weergavemodus" voor me

![image](https://user-images.githubusercontent.com/16559999/208170133-044dd4c7-ceb5-47c2-9eee-0bb2a57029d7.png)

**Comment by luukverhoeven** [comment]
Indicatie 2h werk

**Comment by gemguardian** [comment]
Bedankt . ik heb het doorgeven aan de klant. Wachten daar het antwoord even van af.
