### ISSUE TITLE
Core changes to External API + Check M4.1/php 8

### ISSUE THREAD

**Issue by gemguardian** [Lesterhuis-Training-en-Consultancy/moodle-block_fastnav#2]
@luukverhoeven zoals besproken zou je het onderstaande voor FastNav block willen doen? Heb ik al een php8/M4.1 test gedaan en geen bijzonderheden geconstateerd. 

Move lib/externallib.php to namespaced classes and fix coding style, etc.) https://tracker.moodle.org/browse/MDL-76583

moodle-block_fastnav: classes/external.php

de 1 uur voor aanpassen en de max 2 uur voor M4.1 / php 8 check zijn akkoord.

**Comment by luukverhoeven** [comment]
Toegevoegd aan de planning.

**Comment by gemguardian** [comment]
@luukverhoeven heb jij enige idee wanneer ik het kan verwachten dan kan ik het ook aan mijn planning toevoegen.

**Comment by luukverhoeven** [comment]
Ingepland voor 31 maart

**Comment by luukverhoeven** [comment]
@gemguardian Te testen in https://github.com/Lesterhuis-Training-en-Consultancy/moodle-block_fastnav/tree/860pzp2ar_core_changes_moodle4php8

Ik hoor graag of de aanpassingen akkoord zijn. Dan zet ik deze door naar master/main.

**Comment by gemguardian** [comment]
@luukverhoeven akkoord

**Comment by luukverhoeven** [comment]
Doorgezet naar de master. Zal ik deze ook bijwerken op moodle.org?

**Comment by gemguardian** [comment]
Graag



Verzonden vanaf mijn Galaxy



-------- Oorspronkelijk bericht --------
Van: Luuk Verhoeven ***@***.***>
Datum: 22-03-2023 22:18 (GMT+01:00)
Aan: Lesterhuis-Training-en-Consultancy/moodle-block_fastnav ***@***.***>
Cc: Gemma Lesterhuis ***@***.***>, Assign ***@***.***>
Onderwerp: Re: [Lesterhuis-Training-en-Consultancy/moodle-block_fastnav] Core changes to External API + Check M4.1/php 8 (Issue #2)


Doorgezet naar de master. Zal ik deze ook bijwerken op moodle.org?

**Comment by luukverhoeven** [comment]
@gemguardian Done
