### ISSUE TITLE
Oplevering Moodle 4.2 + PHP 8.0

### ISSUE THREAD

**Issue by luukverhoeven** [Lesterhuis-Training-en-Consultancy/moodle-block_fastnav#4]
Graag informeren wij jullie over de oplevering van de Moodle plug-in(s) en eventuele aanpassingen die jullie hebben aangevraagd. Zouden jullie de functionaliteit ervan kunnen controleren en nagaan of alles naar verwachting werkt? Eventuele vragen of opmerkingen vernemen wij graag.

Bijgevoegd vinden jullie de links naar de repositories:

https://github.com/Lesterhuis-Training-en-Consultancy/moodle-block_fastnav/tree/86bwwnb0j-MOODLE42

Na jullie testen zien we graag jullie akkoord tegemoet voor het doorvoeren van de wijzigingen naar de main/master branch.

**Comment by gemguardian** [comment]
@luukverhoeven dit is akkoord - getest op PHP 8.1/M4.2

1. Graag de main 4.1 versie maken
2. Graag dit de nieuwe main maken
3. Kun je dit ook doorzetten naar Moodle.org ? 
Bedankt!

**Comment by luukverhoeven** [comment]
@gemguardian 1, 2  en 3 doorgevoerd.
