### ISSUE TITLE
Early bird upgrade M 4.4 and 4.3

### ISSUE THREAD

**Issue by luukverhoeven** [Lesterhuis-Training-en-Consultancy/moodle-block_fastnav#6]
Graag informeren wij jullie over de oplevering van de Moodle plug-in(s) en eventuele aanpassingen die jullie hebben aangevraagd. Zouden jullie de functionaliteit ervan kunnen controleren en nagaan of alles naar verwachting werkt? Eventuele vragen of opmerkingen vernemen wij graag.

Bijgevoegd vinden jullie de links naar de repositories:

https://github.com/Lesterhuis-Training-en-Consultancy/moodle-block_fastnav/tree/86bwwnckq-MOODLE44

Na jullie testen zien we graag jullie akkoord tegemoet voor het doorvoeren van de wijzigingen naar de main/master branch.

**Comment by luukverhoeven** [comment]
@gemguardian We hebben de plug-in nu ook in 4.3 getest en README aangepast, deze aanpassing staat klaar in https://github.com/Lesterhuis-Training-en-Consultancy/moodle-block_fastnav/tree/86by49r4k-MOODLE43

**Comment by gemguardian** [comment]
> @gemguardian We hebben de plug-in nu ook in 4.3 getest en README aangepast, deze aanpassing staat klaar in https://github.com/Lesterhuis-Training-en-Consultancy/moodle-block_fastnav/tree/86by49r4k-MOODLE43

@luukverhoeven  Moodle 4.3 is getest en kan een aparte branche krijgen, zet je deze meteen door naar Moodle.org?

**Comment by gemguardian** [comment]
@luukverhoeven kunnen jullie aub voor M44 het volgende controleren. Ik denk dat het te maken heeft met een wijziging van moodle op de cursus pagina

Ik heb het blok toegevoegd aan Startpagina, maar toont niet op de cursus pagina. 
Als je het op cursuspagina niveau toevoegt werkt het ook niet. 

![image](https://github.com/Lesterhuis-Training-en-Consultancy/moodle-block_fastnav/assets/16559999/226e7b26-700c-422d-9d76-4f625233e7b1)


![image](https://github.com/Lesterhuis-Training-en-Consultancy/moodle-block_fastnav/assets/16559999/72c231d2-7c9f-4b0e-9ba1-f4e4a595115e)

**Comment by luukverhoeven** [comment]
@gemguardian Kun je bovenstaande branch nog eens controleren.? We hebben er een stuk eruit gehaald. Het lijkt dat het blok anders niet gerenderd wordt. 

https://github.com/Lesterhuis-Training-en-Consultancy/moodle-block_fastnav/commit/056cb93d49aaf7e08ae62dcd779ca3ec25c8f962

**Comment by gemguardian** [comment]
@luukverhoeven dit werkt

**Comment by luukverhoeven** [comment]
@gemguardian Mag dit door naar master en moodle.org?

**Comment by gemguardian** [comment]
@luukverhoeven yup dat is akkoord

**Comment by luukverhoeven** [comment]
@gemguardian Doorgezet
